DELETE http://localhost:8080/api/blogs/63644a24f50114a61bd88d68
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2MzY0MTdlOGYxZDk3YTRkZWFkZjlhNzQiLCJpYXQiOjE2Njc1MTY2OTEsImV4cCI6MTY2NzUyMDI5MX0.nGJQf-cyN3ql4Vjlq9M_f4B5Ot0In6XAPmDPinOW1vE

###
POST http://localhost:8080/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2MzY0MTdlOGYxZDk3YTRkZWFkZjlhNzQiLCJpYXQiOjE2Njc1MTY2OTEsImV4cCI6MTY2NzUyMDI5MX0.nGJQf-cyN3ql4Vjlq9M_f4B5Ot0In6XAPmDPinOW1vE

{
  "title": "third blog with authorization",
  "author": "marting fowler",
  "userId": "636417e8f1d97a4deadf9a74",
  "url": "url"
}

###
GET http://localhost:8080/api/blogs