# TO LOCALHOST

### all notes
GET http://localhost:8080/api/notes/

### valid id
GET http://localhost:8080/api/notes/635d75d0957d011fb3e334b5

### id not stored
GET http://localhost:8080/api/notes/5c41c90e84d891c15dfa3431

### malformatted id
GET http://localhost:8080/api/notes/635d75d0957d011fb3e33ads

### post note
POST http://localhost:8080/api/notes
Content-Type: application/json

{
  "content": "VSCode REST client is very convenient",
  "important": false
}

### post note
POST http://localhost:8080/api/notes
Content-Type: application/json

{
  "content": "abc",
  "important": false
}

###
PUT http://localhost:8080/api/notes/635e9bfb1caab8f6caa10754
Content-Type: application/json

{
  "content": "updated content",
  "important": true
}

###
PUT http://localhost:8080/api/notes/635e9bfb1caab8f6caa10754
Content-Type: application/json

{
  "content": "abc",
  "important": true
}

### delete
DELETE http://localhost:8080/api/notes/635db11ae88c7e43d7115331

# TO FLY.IO ENDPOINT

###
GET https://notes-backend-3176481.fly.dev/api/notes
